apiVersion: v1
kind: Service
metadata:
  namespace: defi-providers
  name: defi-providers
spec:
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    component: defi-providers
