name: Node.js CI

on:
  pull_request:
    branches: ["master"]
  push:

jobs:
  build:
    runs-on: dappradar-runner

    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: test
