name: Node.js CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Protoc Install
        run: curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip
      - name: Unzip Protoc
        run: unzip -o protoc-3.14.0-linux-x86_64.zip -d ./proto
      - name: Chmod Protoc
        run: chmod 755 -R ./proto/bin
      - name: Build
        run: npm run build
