name: Node.js CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: test
