name: Node.js CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: docker build -t test .
      - name: Run
        run: docker run test
