name: Node.js CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -   name: Build and push docker image
          uses: docker/build-push-action@v1
          with:
            dockerfile: Dockerfile
            tag_with_ref: true
