name: Deploy to production.

on:
  push:
    branches: [ DEVOPS-1167 ]
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: dappradar-runner

    env:
      PACKAGE_DIR: build-artifacts/defi-tracker.tar.gz
      DESTINATION_PATH: /opt/defi-providers

    steps:
      - uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package project
        run: |
          mkdir -p ${{ github.workspace }}/build-artifacts
          tar --exclude-vcs -zcpvf ${{ env.PACKAGE_DIR }} -C ${{ github.workspace }}  dist/ proto/ node_modules/ package.json package-lock.json

      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: dappradar/dappradar-cicd-ansible
          ref: master
          ssh-key: ${{ secrets.CICD_REPO_DEPLOYMENT_KEY }}
          path: cicd-ansible

      # TODO: add manual approval step

      # TODO: get .env file content from AWS parameters store

      - name: Run deployment playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: prod-cicd-defi-providers-deployment.yml
          # Optional, directory where playbooks live
          directory: ${{ github.workspace }}/cicd-ansible
          # Optional, SSH private key
          key: ${{ secrets.CICD_REPO_DEPLOYMENT_KEY }}
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory hosts
            --extra-vars ansible_user=root
            --extra-vars ansistrano_deploy_from=${{ github.workspace }}/${{ env.PACKAGE_DIR }}
            --extra-vars ansistrano_deploy_to=${{ env.DESTINATION_PATH }}
            --verbose
